### ISSUE TITLE
are this code can be run in the windows and what is the difference between BSDS500

### ISSUE THREAD

**Issue by forrestsz** [jponttuset/seism#7]
Hi, thanks for your excellent work and code.
i want to know does this code can be run under windows(because the BSDS500 only can be run in linux) and what is the difference between your work and the official BSDS500 bench.
thank!

**Comment by jponttuset** [comment]
Yes, it can run under Windows, it comes precompiled for Windows, Mac, and Linux.
Differences with the BSDS500 'official' code are:
1) There is an extra metric (Fop) that we suggested in:
Supervised Evaluation of Image Segmentation and Object Proposal Techniques
Jordi Pont-Tuset and Ferran Marques, TPAMI 2015.
2) The 'official' metric (Fb) uses Piotr Dollar's implementation, which can run on Windows, instead of the official one that cannot.

**Comment by forrestsz** [comment]
Thank for your reply! now, i am using the BSDS500 evaluate code repo by https://github.com/BIDS/BSDS500,
i just use the metric including boundary based(F,PR) and region based(SegmentationCovering, RI, VoI). I want to use your code in windows, so i want to know if has any different between your code and BSDS500 repo version in those metric. thank you!

**Comment by jponttuset** [comment]
My code has only Fb and Fop, not the rest.
Piotr's implementation of Fb does not match 100% that of BSDS500 but the differences are not significant.
I would recommend using Fb and Fop as the only metrics to evaluate performance, as I show their superiority in the following paper:
Supervised Evaluation of Image Segmentation and Object Proposal Techniques
Jordi Pont-Tuset and Ferran Marques, TPAMI 2015.

**Comment by forrestsz** [comment]
thank for your suggestion, i would read the paper carefully.
